version: '3.7'
services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:/app/node_modules:cached'
    links:
      - backend
    environment:
      - NODE_ENV=development
    ports:
    - 3000:3000
